lenguage: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t pascale/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pascale/docker-react npm run test
